# Generated by Django 5.2.2 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0052_remove_rasterstyle_rendering_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='legend_from_capabilities',
            field=models.BooleanField(default=False, help_text='If checked, the legend will be loaded from the WMS GetCapabilities response (LegendURL). This takes precedence over custom legend options above.', verbose_name='Load legend from WMS capabilities'),
        ),
    ]
