# Generated by Django 5.2.2 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0053_wmslayer_legend_from_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectortilelayer',
            name='is_pmtiles',
            field=models.BooleanField(default=False, help_text='Check if the URL points to a PMTiles file instead of XYZ tiles', verbose_name='PMTiles format'),
        ),
    ]
